flowchart LR
    A[Endevor] -->|done manually once a month| B[GITHUB]
    B -->|Commit and Push| C[Harness]
    C -->|upload mainframe code to S3<br/>in enterprise-integration account| D[S3]
    C -->|Harness trigger aws transform comment| E[AWS Transform]
    E -->|AWS Transform write output<br/>back to S3| D
    D -->|Kiro can read analysis<br/>from aws transform| F[KIRO]
