---
- name: Include present tasks for LiteLLM gateway
  ansible.builtin.include_tasks: present.yml
  when: k3s_litellm_gateway_state == 'present'

- name: Include absent tasks for LiteLLM gateway
  ansible.builtin.include_tasks: absent.yml
  when: k3s_litellm_gateway_state == 'absent'
