---
full_name: "{{ lookup('env', 'GIT_AUTHOR_NAME') | default(lookup('env', 'USER'), true) | default('user', true) }}"
git_email: "1589359+doesitscript@users.noreply.github.com"
git_user: "{{ lookup('env', 'GITHUB_USER') | default(lookup('env', 'USER'), true) | default('user', true) }}"
git_signing_key: ""
