- name: Process hub role for macOS
  ansible.builtin.import_tasks: mac.yml
  when: ansible_system == "Darwin"

- name: Process hub role for Ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Process hub role for Windows
  ansible.builtin.import_tasks: windows.yml
  when: ansible_system == "Windows"
