---
argument_specs:
  main:
    short_description: Install and verify Microsoft Remote Desktop on macOS.
    options:
      remote_desktop_mac_tap_name:
        type: str
        default: junian/homebrew-mirrors
      remote_desktop_mac_cask_name:
        type: str
        default: microsoft-remote-desktop-for-macos12
      remote_desktop_mac_app_path:
        type: str
        default: /Applications/Microsoft Remote Desktop.app
      remote_desktop_mac_pkg_id:
        type: str
        default: com.microsoft.rdc.macos
      remote_desktop_mac_verify_install:
        type: bool
        default: true
      remote_desktop_mac_attempt_stabilization:
        type: bool
        default: false
      remote_desktop_mac_enforce_stabilization:
        type: bool
        default: false
      remote_desktop_mac_stabilization_become:
        type: bool
        default: false
