- name: Process package manager role for Ubuntu
  ansible.builtin.include_tasks: ubuntu.yml
  when:
    - >-
      (
        ansible_facts.get('distribution', '')
        if (ansible_facts | default({})) is mapping
        else ''
      ) == "Ubuntu"
      or (ansible_distribution | default('')) == "Ubuntu"

- name: Process package manager role for macOS
  ansible.builtin.include_tasks: mac.yml
  when:
    - >-
      (
        ansible_facts.get('system', '')
        if (ansible_facts | default({})) is mapping
        else ''
      ) == "Darwin"
      or (ansible_system | default('')) == "Darwin"

- name: Process package manager role for Windows
  ansible.builtin.include_tasks: windows.yml
  when:
    - >-
      (
        ansible_facts.get('system', '')
        if (ansible_facts | default({})) is mapping
        else ''
      ) in ["Windows", "Win32NT"]
      or (ansible_system | default('')) in ["Windows", "Win32NT"]
