---
- name: Remove Semaphore stack
  community.docker.docker_compose_v2:
    project_src: "{{ ansible_ui_semaphore_data_path }}"
    state: absent
    remove_volumes: "{{ ansible_ui_semaphore_remove_volumes_on_absent }}"
