---
repos:
  - repo: local
    hooks:
      - id: ansible-quality-gate
        name: ansible quality gate
        entry: ./bin/ansible-quality-gate.sh
        language: system
        pass_filenames: true
        files: >-
          (^playbooks/.*\.(yml|yaml)$)|
          (^roles/.*/(tasks|handlers|defaults|vars|meta)/.*\.(yml|yaml)$)|
          (^inventory/.*\.(yml|yaml)$)
