---
ansible_host: "DESKTOP-VLLM"
ansible_port: 5985
surface_type: "windows_host"
host_ip: "192.168.50.158"
ansible_connection: "winrm"
winrm_port: 5985
win_user: "josh"
ansible_user: "josh"
physical_node: "server-225"
win_password: "Pass@w0rd1"
ansible_winrm_server_cert_validation: "ignore"
ansible_winrm_scheme: "http"
ansible_winrm_transport: "ntlm"
