---
transport_execnode_ssh_dir: "{{ lookup('env','HOME') }}/.ssh"
transport_execnode_ssh_key_basename: "id_ed25519_ansible"
transport_execnode_ssh_private_key_path: "{{ transport_execnode_ssh_dir }}/{{ transport_execnode_ssh_key_basename }}"
transport_execnode_ssh_public_key_path: "{{ transport_execnode_ssh_private_key_path }}.pub"

# optional: manage known_hosts for a list of targets (safe no-op if list empty)
transport_known_hosts_manage: true
transport_known_hosts_targets: []   # list of dicts: [{ name: "hom-lab-hvh-02", host: "1.2.3.4", port: 22 }, ...]
