- name: Process python role for macOS
  ansible.builtin.import_tasks: mac.yml
  when: ansible_facts['system'] == "Darwin"

- name: Process python role for Ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Process python role for Windows
  ansible.builtin.import_tasks: windows.yml
  when: ansible_facts['system'] == "Windows"
