# DEPRECATED — source of truth is templates/codex-multi-terminal.bash.j2
# Kept so old docs that mention files/codex-multi-terminal.bash still resolve.
# Do not edit this file; edit the Jinja template instead.
