@echo off
REM Check if running as Administrator - WSL setup issues
powershell.exe -Command "$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator); if ($isAdmin) { Write-Host ''; Write-Host '╔══════════════════════════════════════════════════════════════════════════════╗' -ForegroundColor Red; Write-Host '║                                                                              ║' -ForegroundColor Red; Write-Host '║                    ⚠️  CRITICAL WARNING ⚠️                                  ║' -ForegroundColor Red; Write-Host '║                                                                              ║' -ForegroundColor Red; Write-Host '║  You are running as Administrator!                                           ║' -ForegroundColor Yellow; Write-Host '║                                                                              ║' -ForegroundColor Red; Write-Host '║  Running this script as Administrator causes issues with WSL setup.         ║' -ForegroundColor Yellow; Write-Host '║                                                                              ║' -ForegroundColor Red; Write-Host '║  Please run this script with a regular (non-Administrator) user account.    ║' -ForegroundColor Yellow; Write-Host '║                                                                              ║' -ForegroundColor Red; Write-Host '╚══════════════════════════════════════════════════════════════════════════════╝' -ForegroundColor Red; Write-Host ''; Write-Host 'Press any key to continue anyway (NOT RECOMMENDED) or Ctrl+C to exit...' -ForegroundColor Yellow; $null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown'); Write-Host '' }"

REM Set PowerShell execution policy to Bypass permanently for CurrentUser
powershell.exe -Command "Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser -Force"

REM Run the PowerShell bootstrap script
powershell.exe -ExecutionPolicy Bypass -File "%~dp0bootstrap_inventory.ps1"
