---
argument_specs:
  main:
    short_description: Manage periodic filesystem-capacity checks
    options:
      storage_capacity_monitor_state:
        type: str
        choices: [present, absent]
      storage_capacity_monitor_warning_percent:
        type: int
      storage_capacity_monitor_critical_percent:
        type: int
      storage_capacity_monitor_mounts:
        type: list
        elements: dict
        options:
          path:
            type: str
            required: true
          required:
            type: bool
            default: true
      storage_capacity_monitor_timer_calendar:
        type: str
      storage_capacity_monitor_randomized_delay_seconds:
        type: int
      storage_capacity_monitor_require_alloy:
        type: bool
      storage_capacity_monitor_journal_system_max_use:
        type: str
      storage_capacity_monitor_script_path:
        type: path
      storage_capacity_monitor_service_name:
        type: str
      storage_capacity_monitor_timer_name:
        type: str
