---
- name: Build Red Hat Ansible MCP from source (macOS)
  ansible.builtin.import_tasks: install_mac.yml
  when: ansible_os_family == "Darwin"

- name: Build Red Hat Ansible MCP from source (Ubuntu)
  ansible.builtin.import_tasks: install_ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Build Red Hat Ansible MCP from source (Windows)
  ansible.builtin.import_tasks: install_windows.yml
  when: ansible_os_family == "Windows"
