---
# tmux – main task dispatcher

- name: Install and configure tmux on macOS
  ansible.builtin.import_tasks: mac.yml
  when: ansible_facts['system'] == "Darwin"

- name: Install and configure tmux on Ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install and configure tmux on Windows
  ansible.builtin.import_tasks: windows.yml
  when: ansible_facts['system'] == "Windows"
