---
# SPDX-License-Identifier: MIT-0
galaxy_info:
  author: doesitscript
  description: Deploy Langfuse platform on K3s
  company: doesitscript
  license: MIT
  min_ansible_version: "2.14"
  galaxy_tags: []

dependencies: []
