---
- name: Include present tasks for K3s Ollama runtime
  ansible.builtin.include_tasks: present.yml
  when: k3s_ollama_runtime_state == 'present'

- name: Include absent tasks for K3s Ollama runtime
  ansible.builtin.include_tasks: absent.yml
  when: k3s_ollama_runtime_state == 'absent'
