---
remote_desktop_mac_tap_name: junian/homebrew-mirrors
remote_desktop_mac_cask_name: microsoft-remote-desktop-for-macos12
remote_desktop_mac_app_path: /Applications/Microsoft Remote Desktop.app
remote_desktop_mac_pkg_id: com.microsoft.rdc.macos

remote_desktop_mac_verify_install: true
remote_desktop_mac_attempt_stabilization: false
remote_desktop_mac_enforce_stabilization: false
remote_desktop_mac_stabilization_become: false
