---
k3s_node_gpu_prereqs_state: present
k3s_node_gpu_prereqs_expected_resource: nvidia.com/gpu
k3s_node_gpu_prereqs_expected_count: 1
k3s_node_gpu_prereqs_node_name: "{{ inventory_hostname }}"
k3s_node_gpu_prereqs_kubeconfig: /etc/rancher/k3s/k3s.yaml
