---
- name: Validate K3s GPU infrastructure prerequisites
  hosts: hom-lab-ctl-k3s-02
  gather_facts: false
  become: false

  roles:
    - role: k3s_node_gpu_prereqs
      tags:
        - k3s_node_gpu_prereqs
        - gpu_infra
        - ai_ml_platform
