---
- import_playbook: hyperv_ubuntu_gpu_p_runtime_artifact_pipeline.yaml
  vars:
    hyperv_ubuntu_gpu_p_runtime_windows_hosts: hom-lab-ctl-hvh-02
    hyperv_ubuntu_gpu_p_runtime_guest_hosts: hom-lab-ctl-k3s-02
    hyperv_ubuntu_gpu_p_runtime_guest_vm_name: hom-lab-ctl-k3s-02
