---
argument_specs:
  main:
    short_description: Manage mac-dev /etc/hosts from Traefik registry and router workaround
    options:
      homelab_hosts_file_mac_enabled:
        type: bool
        default: false
      homelab_hosts_file_mac_galaxy_role:
        type: str
        default: hosts_file
