---
argument_specs:
  main:
    short_description: Deploy NetBox using Docker Compose
    options:
      ipam_netbox_state:
        type: str
        description: The desired state of the NetBox stack.
        choices:
          - present
          - absent
        default: present
      ipam_netbox_version:
        type: str
        description: The version of NetBox to deploy.
        default: v4.0.2
      ipam_netbox_data_path:
        type: str
        description: The path on the host to store NetBox data.
        default: /opt/netbox
      ipam_netbox_user:
        type: str
        description: The user that should own the data directories.
        default: root
      ipam_netbox_group:
        type: str
        description: The group that should own the data directories.
        default: root
      ipam_netbox_http_port:
        type: str
        description: The port mapping for the NetBox web interface.
        default: "8000:8080"
      ipam_netbox_remove_volumes_on_absent:
        type: bool
        description: Whether to remove Docker volumes when the stack is removed.
        default: false
