---
# Variables for all hosts
timezone: America/Chicago  # POSIX timezone (for macOS/Linux)
timezone_windows: Central Standard Time  # Windows timezone name
contract_file: contracts/fuzlang.contract.yaml
