---
argument_specs:
  main:
    short_description: Install fzf-tab-completion for bash and optional Python REPL
    options:
      fzf_tab_completion_state:
        type: str
        required: false
        default: absent
        choices:
          - present
          - absent
